
image:
  host: "" # 192.168.1.135:8888
  pullSecrets: []

service:
  type: ClusterIP
  port: 80
  internalPort: %ServicePort%
  probeUri: "/heartbeat"

podAnnotations:
  proxy.istio.io/config: |
    holdApplicationUntilProxyStarts: true

replicaCount: 1
resources: {}
