
image:
  host: "" # 192.168.1.135:8888
  pullSecrets: []

service:
  type: ClusterIP
  port: 80
  internalPort: %ServicePort%
  probeUri: "/heartbeat"

replicaCount: 1
resources:
  limits:
    cpu: 4000m
    memory: 2000Mi
  requests:
    cpu: 900m
    memory: 500Mi

