
image:
  host: "" # 192.168.1.135:8888
  pullSecrets: []

service:
  type: ClusterIP
  port: 80
  internalPort: %ServicePort%
  probeUri: "/heartbeat"
resources:
  limits:
    cpu: 900m
    memory: 500Mi
  requests:
    cpu: 4000m
    memory: 2000Mi

replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
